"""empty message

Revision ID: 74e324257411
Revises: 
Create Date: 2024-03-12 12:43:12.471339

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74e324257411"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("short_url", sa.UUID(), nullable=False),
        sa.Column("original_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("short_url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group")
    # ### end Alembic commands ###
